### ISSUE TITLE
Coupons Gem is not compatible with rails 3.2.17

### ISSUE THREAD

**Issue by vibhoo** [fnando/coupons#3]
I tried using gem with rails 3.2.17 but there was no success, is there a issue with gem or I'm missing something?

**Comment by roshan92** [comment]
Please give any errors to get help. Thank you. :)

**Comment by fnando** [comment]
The gem has hard dependency on Rails 4.2+. I don't know if it works on older Rails versions because all my apps run in latest Rails version.

**Comment by vibhoo** [comment]
@fnando thanks for your reply :+1:
