### ISSUE TITLE
Request/suggestion: Unique codes

### ISSUE THREAD

**Issue by cabgfx** [fnando/coupons#8]
What do you think of having the `Coupon` model enforce uniqueness for the coupon code?

As it is today, I can create multiple coupons with the same name. I suspect this is why the larger/smaller discount finders exist?

But could they be eliminated altogether, by having `Coupons::Models::Coupon` use `validates_uniqueness_of :name` ?

**Comment by fnando** [comment]
My rationale is having same coupons but with different rules. Since you can create your own coupon finder, you can do whatever you want (imagine using the same coupon for when you add product A or product B, but with different discount values based on different rules you may define).

Makes sense?

**Comment by cabgfx** [comment]
Sure, I can see why it would make sense to keep it as flexible as possible here.

Is there a clean way you’d suggest I add uniqueness in my project?

(this also answers #7 for me, feel free to close)

**Comment by fnando** [comment]
I would create a migration that adds the unique index. Then I'd add a validation like the following:

``` ruby
# config/initializers/coupons.rb
Coupons::Models::Coupon.validates_uniqueness_of :code
```

**Comment by cabgfx** [comment]
Thanks!
